### PR TITLE
Merge lib.rs into main.rs

### PR DESCRIPTION
**Pull request by mkroening**

### CODE REVIEW

**Comment by mkroening** [comment]
1. The loader is never used as a library, only as an executable.
2. If we would make it a proper library, we would have to properly design the API surface that the crate exposes.
3. Having a properly designed API surface (or none at all in this case) makes it possible to detect more dead code.
4. In my opinion it is easier to read one main.rs instead of two files if I only want to understand the executable use case since the library one does not exist.

**Comment by jounathaen** [comment]
I can approve this!

**Review by stlankes — APPROVED** [review]

**Comment by mkroening** [comment]
bors r=stlankes

**Comment by stlankes** [comment]
@mkroening CI failed

**Comment by mkroening** [comment]
Ah, yes. That error is unrelated to the PR. I'll look into it. :+1:

**Comment by mkroening** [comment]
bors r=stlankes

**Pull request merged**
